### ISSUE TITLE
DAG not found in serialized_dag table

### ISSUE THREAD

**Issue by nvn01234** [epoch8/airflow-exporter#98]
Step by step to reproduce the bug:
- Step 1: Delete a dag in code
- Step 2: Do not delete the DAG on the UI, wait for it disappeared on the UI
- Step 3: Go to admin/metrics, you will get the bug as the picture below
![image](https://user-images.githubusercontent.com/16082537/121623402-d3f83c00-ca99-11eb-80d9-f0c3632eaa3a.png)

Currently I have to run a CLI command: `airflow dags delete <dag_id>` to completely remove all records related to a deleted dag

The solution can be: Ignore the deleted dags (don't show them in metrics)

/label ~bug

**Comment by elephantum** [comment]
Interesting, thanks for reporting.

**Comment by biryukovsky** [comment]
I had a similar problem. In my case the exception message was like "airflow.exception.SerializedDagNoFound: DAG 'None' in serialized_dag table". Fixed with following query in airflow database:
`DELETE FROM dag_run WHERE dag_id IS NULL;`

**Comment by elephantum** [comment]
Hi, everyone!

If anyone would have time to create a PR that fixes it, I would be grateful. Fix should not be too complex.

**Comment by sawaca96** [comment]
@elephantum How should I fix it?
just fix it to ignore `airflow.exceptions.SerializedDagNotFound` ?

**Comment by elephantum** [comment]
I would suggest altering sqlalchemy query for this case, most probably simple join with dag table would be enough.

I.e. filter out such tasks and dags that do not have corresponding dag in DB.

**Comment by sawaca96** [comment]
@elephantum  #105 I create PR 
Thank you for the opportunity.😁😁

**Comment by CyberHippo** [comment]
Experienced it as well.

**Comment by baryluk** [comment]
Same issue here, with airflow-exporter 1.5.1,

and airflow 1.10.15, (where for some very old dags we do not have `serialized_dag` entries, as we only enabled that option few weeks ago in preparation for the Airflow 2.x update), but it will be an issue when I upgrade to 2.x, because we will be preserving full history.

I have a single dag in `dag` table, that is no longer available. Looking at postgresql database it has is_paused false, is_subdag false, is_active false.

**Comment by elephantum** [comment]
Fixed in v1.5.2

**Comment by baryluk** [comment]
Excellent, it works. Thanks @sawaca96 and @elephantum
